apiVersion: v1
kind: Namespace
metadata:
  name: gavel
  labels:
    app.kubernetes.io/part-of: gavel
---
apiVersion: v1
kind: Namespace
metadata:
  name: gavel-ai
  labels:
    app.kubernetes.io/part-of: gavel
